test-warnings: true
strictness: veryhigh

ignore-paths:
  - README.md
  - build

ignore-patterns:
  - .+/migrations/.+

pylint:
  disable:
    - unused-argument
    - too-few-public-methods
    - too-many-arguments
    - too-many-ancestors
    - redefined-outer-name
