version: '3'
services:
  db:
    image: postgres:9
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apiqa-storage
    ports:
      - 5438:5432
  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: examplekey
      MINIO_SECRET_KEY: examplekey
    ports:
      - 9010:9000
